kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: my-pvc-readings
spec:
  storageClassName: my-storage-class
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi