apiVersion: apps/v1
kind: Deployment                                          
metadata:
  name: tr-microservice
spec:
  selector:                                              
    matchLabels:
      app: tr-microservice
  replicas: 1                                         
  minReadySeconds: 15
  strategy:
    type: RollingUpdate                                   
    rollingUpdate: 
      maxUnavailable: 0                                   
      maxSurge: 1                                        
  template:                                               
    metadata:
      labels:
        app: tr-microservice                                  
    spec:
      containers:
        - image: thushanijay/temprature-reader-ms:new
          imagePullPolicy: Always                        
          name: tr-microservice
          ports:
            - containerPort: 8003
          volumeMounts:
            - name: readings
              mountPath: /readings
      volumes:
        - name: readings
          persistentVolumeClaim:
            claimName: my-pvc-readings