apiVersion: apps/v1
kind: Deployment
metadata:
  name: humidity-microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: humidity-microservice
  template:
    metadata:
      labels:
        app: humidity-microservice
    spec:
      containers:
        - name: humidity-microservice
          image: thushanijay/humidity-microservice:latest
          ports:
            - containerPort: 8004
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"