apiVersion: v1
kind: Service
metadata:
  name: humidity-microservice
spec:
  selector:
    app: humidity-microservice
  ports:
    - name: http
      port: 8004
      targetPort: 8004
  type: ClusterIP
