apiVersion: v1
kind: Pod
metadata:
  name: humidity-microservice-pod
spec:
  containers:
  - name: humidity-microservice-container
    image: humidity-microservice-image
    ports:
    - containerPort: 8004
    volumeMounts:
    - name: shared-data
      mountPath: /app/readings
  volumes:
  - name: shared-data
    persistentVolumeClaim:
      claimName: shared-pvc
